services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: memex-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: memex-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  rabbitmq:
    image: rabbitmq:3-management
    container_name: memex-rabbitmq
    ports:
      - "5672:5672" # The RabbitMQ port
      - "15672:15672" # The Dashboard port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  minio:
    image: quay.io/minio/minio
    container_name: memex-minio
    ports:
      - "9000:9000" # API Port (Java talks to this)
      - "9001:9001" # Console Port (You login here)
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  app:
    build: .
    container_name: memex-app
    ports:
      - "8080:8080"
    environment:
      # CONNECT TO RABBITMQ
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      
      # CONNECT TO ELASTICSEARCH
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
      
      # CONNECT TO MINIO (S3)
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=admin
      - S3_SECRET_KEY=password
      - S3_BUCKET_NAME=memex-files
    depends_on:
      - elasticsearch
      - rabbitmq
      - minio
volumes:
  es-data:
  minio-data: