global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'memex-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']